name: Release Pipeline

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./target/release/lodestone_cli
          name: lodestone_cli

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/release/lodestone_cli
          tag_name: ${{ github.ref_name }}
          body: "This is a release build from ${{ github.ref_name }}."
          draft: true
          prerelease: true
